dist:     trusty    # èñïîëüçóåì Ubuntu 14.04 Trusty Tahr (à íå 12.02 Precise Pangolin)
sudo:     required  # èñïîëüçóåì Virtual Machine (à íå Docker container)

language: cpp       # íà ïðàêòèêå ðàçíèöû ìåæäó ñïåöèôè÷íûì äëÿ C++ îêðóæåíèåì
                    # è, ñêàæåì, python -- íèêàêîé. Íî ïóñòü áóäåò cpp.

deploy:
    # âûêëàäûâàåì tagged-êîììèòû íà GitHub Releases:
    provider:     releases
    file:         <package-file>
    skip_cleanup: true
    overwrite:    true

    api_key:
        secure:   <encrypted-github-token>

    on:
        tags:     true
